apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e6w3voypt-nodejs-gitops
  description: This is GitOps manifest for e6w3voypt-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=e6w3voypt-nodejs
    backstage.io/kubernetes-id: e6w3voypt-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: e6w3voypt-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:e6w3voypt-nodejs
